### ISSUE TITLE
5px overflow in borderless mode when window is maximized.

### ISSUE THREAD

**Issue by shenzhigang** [melak47/BorderlessWindow#14]
Tested in win7 and win10.
![maximized](https://user-images.githubusercontent.com/8005935/27721139-f51cea86-5d90-11e7-9a59-2f04c85cefdc.jpg)
![normal](https://user-images.githubusercontent.com/8005935/27721140-f6c7acea-5d90-11e7-88a9-37d1e2b37247.jpg)

**Comment by melak47** [comment]
This is normal - part of the window frame spills beyond the screen when maximized.
Since we are expanding the client area to the whole window, it spills as well.
You can calculate the precise amount by getting the `RECT` for the current/closest `HMONITOR` of the window and the window's `RECT`, and taking the difference between `monitor.top` and `window.top`.

Then you could compensate manually for this effect.
It might also be possible to adjust the client rect's top in `WM_NCCALCSIZE` by that amount, which should resolve it without any manual offsetting. I'll try to see if that works later.

**Comment by melak47** [comment]
Adjusting the client rectangle to the monitor *work* rectangle (excludes the task bar) when maximized fixes the problem, and doesn't require the user to be aware of it.

Compare before:
![before](https://user-images.githubusercontent.com/3340026/27745117-70be34f2-5dc2-11e7-846d-bb566e82479a.png)

And After:
![after](https://user-images.githubusercontent.com/3340026/27745122-757e69a8-5dc2-11e7-98cb-de35d1a1b6a0.png)

Under some circumstances you could even see the window spilling onto other screens and under the task bar, though I can't always reproduce it. This fixes that, too.
